<?php

namespace App\Http\Controllers\HistoriaClinica;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;

class IngresoNeonatoController extends Controller
{
    public function informacionIngresoRegistrar(Request $request)
    {
        $idUsuario = $request->session()->get('sesionActual.idTercero'); 

        $parametros = [$request->ingreso, $idUsuario,
                       $request->idTipoIdentificacionMad,$request->identificacionMad,
                       $request->NombresMad,$request->apellidosMad,
                       $request->fechaNacimientoMad,$request->idPaisMad,
                       $request->idDepartamentoMad,$request->idMunicipioMad,
                       $request->idEstadoCivilMad,$request->idgrupoSanguineoMad,
                       $request->direccionMad,$request->telefonoMad,
                       $request->idTipoIdentificacionPat,$request->identificacionPat,
                       $request->NombresPat,$request->apellidosPat,
                       $request->fechaNacimientoPat,$request->idPaisPat,
                       $request->idDepartamentoPat,$request->idMunicipioPat,
                       $request->idEstadoCivilPat,$request->idgrupoSanguineoPat,
                       $request->direccionPat,$request->telefonoPat,
                       $request->combs,$request->habito,
                       $request->nEmbarazo,$request->pTermino,
                       $request->pPrematuro,$request->cesarea,
                       $request->aborto,$request->nVivos,
                       $request->mortinatos,$request->hVivo,
                       $request->fum,$request->fpp,
                       $request->idControlPrenatal,$request->edadGestacional,
                       $request->lugarControlPren,$request->numeroControl,
                       $request->idCultRectoVaginal,$request->resultadoCul,
                       $request->taxoplasma,$request->sifilis ,
                       $request->vih,$request->estreptococo,
                       $request->oSerologias,$request->idMaduracionFetal,
                       $request->dosis,$request->idRiesgoGestacion,
                       $request->fechaMaduracion,$request->medicacion,
                       $request->patologiaMat,$request->observacion,
                       $request->idhospitalario,$request->idextraHospitalario,
                       $request->lParto,$request->idTParto,
                       $request->mCesarea,$request->medicacionCesarea,
                       $request->idinstrumentado,$request->cualInstr,
                       $request->idAmniorrexis,$request->idRpm,
                       $request->horaParto,$request->diasParto,
                       $request->idCantAmniorrexis,$request->idAspecto,
                       $request->observacionAmn,$request->complicacion,
                       $request->idanestecia,$request->tipoAnestecia,
                       $request->dParto,$request->situacion,
                       $request->presentacion,$request->eutocico,
                       $request->distocico,$request->idPizamiento,
                       $request->idCircularCordon,$request->tCircular,
                       $request->idMedicamentoIntrap,$request->cMedicamento,
                       $request->idEstadoFetal,$request->idTipoEstadoFetal,
                       $request->idPielaPiel,$request->mPielaPiel,
                       $request->idPMadre,$request->mPmadre,
                       $request->placenta,$request->idLactanciaM,
                       $request->mLactanciaM,$request->mSigno,
                       $request->mSigno5,$request->mSigno10,
                       $request->mSigno15,$request->dNormal,
                       $request->peg,$request->aeg, //100
                       $request->geg,$request->idCabeza,
                       $request->idPiel,$request->idFontanela,
                       $request->tamañox,$request->idFacie,
                       $request->idOjo,$request->idBocaOrl,
                       $request->idPermacibilidadExo,$request->idClavicula,
                       $request->idCuello,$request->idRespiratorio,
                       $request->idCirculatorio,$request->idRitmo,
                       $request->caracteristicaRitmo,$request->idPulsoFemoral,
                       $request->cualPulso,$request->idAcustica,
                       $request->idAbdomen,$request->miemSupIzquierdo,
                       $request->miemSupDerecho,$request->hepatomegalia,
                       $request->masas,$request->nArteria,
                       $request->esplenomegalia,$request->neflomegalia,
                       $request->idRuido,$request->idDiuresis,
                       $request->idAnoPermeable,$request->configuracion,
                       $request->hemCodo,$request->vdr,
                       $request->profOcular,$request->profUmbilica,
                       $request->profHemorragica,$request->idMSDerecho,
                       $request->idMSIzquierdo,$request->idCadera,
                       $request->caractCadera,$request->idLocomotor,
                       $request->caractLocomoto,$request->idActividad,
                       $request->idTono,$request->idRMoro,
                       $request->idRSuccion,$request->idRBusqueda,
                       $request->idRMarcha,$request->idRPalmar,
                       $request->idRPlantar,$request->idREnderezamiento,
                       $request->idEdadGestacional,$request->idPeso,
                       $request->idDestino,$request->identManilla,
                       $request->porqueManilla,$request->observacionManilla,
                       $request->idtamMetabolico,$request->idTamAuditivo,
                       $request->idTamCardi,$request->idTamVisual,
                       $request->idMuestrade,$request->cualMuestra,
                       $request->emisiones,$request->rtaEncefalico,
                       $request->horaTamizaje,$request->idBGG,
                       $request->porqueBGG,$request->idHepatitisB,$request->porqueHepatitis //169
                       ];
         
        DB::select('EXEC [HistoriaClinica].[spIngresoNeonatalCrear] ?,?,?,?,?,?,?,?,?,?,
                                                                    ?,?,?,?,?,?,?,?,?,?,
                                                                    ?,?,?,?,?,?,?,?,?,?,
                                                                    ?,?,?,?,?,?,?,?,?,?,
                                                                    ?,?,?,?,?,?,?,?,?,?,
                                                                    ?,?,?,?,?,?,?,?,?,?,
                                                                    ?,?,?,?,?,?,?,?,?,?,
                                                                    ?,?,?,?,?,?,?,?,?,?,
                                                                    ?,?,?,?,?,?,?,?,?,?,
                                                                    ?,?,?,?,?,?,?,?,?,?,
                                                                    ?,?,?,?,?,?,?,?,?,?,
                                                                    ?,?,?,?,?,?,?,?,?,?,
                                                                    ?,?,?,?,?,?,?,?,?,?,
                                                                    ?,?,?,?,?,?,?,?,?,?,
                                                                    ?,?,?,?,?,?,?,?,?,?,
                                                                    ?,?,?,?,?,?,?,?,?,?,
                                                                    ?,?,?,?,?,?,?,?,?', $parametros);
  }
}
